#!/bin/sh


# This file is part of scripts.

# scripts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.

# scripts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with scripts.  If not, see <https://www.gnu.org/licenses/>.

# Original author: Maciej Barć (xgqt@protonmail.com)
# Copyright (c) 2020, src_prepare group
# Licensed under the GNU GPL v3 License


trap 'exit 128' INT
set -e
export PATH


pdir="$(git rev-parse --show-prefix)"


FEATURES="sign"
export FEATURES


git add .

if [ -z "${1}" ]
then
    repoman commit
else
    repoman commit -m "${pdir%/}: ${*}"
fi

git pull --verbose
git push --verbose
