#!/bin/sh


# This file is part of scripts.

# scripts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.

# scripts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with scripts.  If not, see <https://www.gnu.org/licenses/>.

# Original author: Maciej Barć <xgqt@riseup.net>
# Copyright (c) 2020, src_prepare group
# Licensed under the GNU GPL v3 License

# Scan with euscan + log
# Requires:
#  - eix
#  - euscan


trap 'exit 128' INT
export PATH


if [ -z "${1}" ]
then
    echo "No overlay names given"
    echo "Please give at least one overlay name as a commandline argument"
    echo "Exiting"
    exit 1
fi

for overlay in "${@}"
do
    for ebuild in $(EIX_LIMIT=0 eix --only-names --in-overlay "${overlay}")
    do 
        euscan --nocolor --quiet "${ebuild}" | tee -a "euscan-${overlay}.log"
    done
    echo ">>> Done scanning ${overlay}"
done
