#!/bin/bash

####################################################
#
# SRC_PREPERE
#
# Marcin Woźniak
# y0rune@aol.com
#
# Last edit: 16-09-2020
#
###################################################

function scanning(){
    EUSCAN=$(euscan --nocolor --quiet $1)
    if [ ! -z "$EUSCAN" ]; then
        echo -e "=============== NOW: $(ls */* | grep -i '.*'$1'.*\.ebuild' | tail -1) ================="
        echo -e "$EUSCAN" | tail -1
    fi
}

function folder(){
    cd $1

    PACKAGES=( $(ls */* | grep -i ":" | sed 's/://g' | awk -F '/' {'print $2'} | sort --unique) )

    for i in ${PACKAGES[@]}
    do
        scanning $i &
    done

    wait $(jobs -p)
    echo -n ">>> Done scanning $1"
}

function nofolder(){
    if [ -z "${1}" ]; then
        echo "No overlay names given"
        echo "Please give at least one overlay name as a commandline argument"
        echo "Exiting"
        exit 1
    fi

for overlay in "${@}"
do
    for ebuild in $(EIX_LIMIT=0 eix --only-names --in-overlay "${overlay}")
    do
        euscan --nocolor --quiet "${ebuild}" | tee -a "euscan-${overlay}.log" &
    done
    wait $(jobs -p)
    echo -n ">>> Done scanning ${overlay}"
done
}

function help(){
    echo "You can use:"
    echo "*   -r or --repo <HERE-REPO-NAME>"
    echo "*   -f or --folder <FOLDER-NAME>"
    echo
    echo "Example of usage"
    echo "./logeuscan -r src_prepare-overlay"
    echo "./logeuscan -f ~/git/src_prepare-overlay"
}

function main(){
    [ $(whereis eix | wc -w) -le "1" ] && { echo "The eix is NOT installed"; exit; }
    [ $(whereis euscan | wc -w) -le "1" ] && { echo "The euscan is NOT installed"; exit; }
    case $1 in
        -h|--help)
            help
            ;;
        -r|--repo)
            nofolder $2
            ;;
        -f|--folder)
            folder $2
            ;;
        *)
        echo "No found variable"; echo; help
    esac
}

main $@
