#!/bin/sh


# Original author: XGQT
# Licensed under the ISC License
# Copyright (c) 2020, src_prepare group


trap 'exit 128' INT
export PATH


main() {
    [ -f Manifest ] && rm -v Manifest
    repoman --verbose manifest

    repoman --verbose -Idx full
    pkgcheck --verbose scan
}


case ${1}
in
    -h | -help | --help )
        echo "Usage: ${0}"
        echo "Performed in this script:"
        echo "1. remove Manifest file"
        echo "2. regen Manifest with 'repoman manifest'"
        echo "3. Check with 'repoman -Idx full'"
        echo "4. Check with 'pkgcheck scan'"
        ;;
    * )
        main
        ;;
esac
