#!/bin/sh


# This file is part of scripts.

# scripts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.

# scripts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with scripts.  If not, see <https://www.gnu.org/licenses/>.

# Original author: Maciej Barć <xgqt@riseup.net>
# Copyright (c) 2020, src_prepare group
# Licensed under the GNU GPL v3 License


trap 'exit 128' INT
export PATH


main() {
    [ -f Manifest ] && rm -v Manifest
    repoman --verbose manifest

    repoman --verbose -Idx full
    pkgcheck --verbose scan
}


case ${1}
in
    -h | -help | --help )
        echo "Usage: ${0}"
        echo "Performed in this script:"
        echo "1. remove Manifest file"
        echo "2. regen Manifest with 'repoman manifest'"
        echo "3. Check with 'repoman -Idx full'"
        echo "4. Check with 'pkgcheck scan'"
        ;;
    * )
        main
        ;;
esac
