#!/bin/sh


trap 'exit 128' INT
export PATH


git submodule update --init --recursive
git submodule update --remote --merge
git add .
git commit -m "submodules update"
git pull --verbose
git push --verbose
